### ISSUE TITLE
[Question] How to set Authentication headers for Elastic Search URL in this.setHost?

### ISSUE THREAD

**Issue by fsaiyedOB** [InnerSearch/vue-innersearch#10]
How to set Authentication headers for Elastic Search URL in this.setHost?

**Comment by TrimA74** [comment]
This is the setHost function definition : 

```javascript
setHost : (host) => {
	Store.commit("Elasticsearch/setHost", new elasticsearch.Client({ host }));
}
```

You can refer to this [SSL and Authentification](http://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/auth-reference.html)

So basically you can do something like this for a Basic Auth : 

```javascript
this.setHost({
         host: 'https://user:password@my-site.com:9200'
});
```

**Comment by ctrngk** [comment]
When I try to setHost like this, none of them are working.

// not working
this.setHost({
        host: 'http://es.yinyan.fr'
});

// not working
this.setHost({
         host: 'http://es.yinyan.fr:80'
});

/* original works
this.setHost({'http://es.yinyan.fr'})
/*

**Comment by TrimA74** [comment]
Try 

```javascript
this.setHost({
     host: "es.yinyan.fr",
     port : 80
});
```

If you are giving an object to this.setHost the default port is 9200 and not 80.
