### ISSUE TITLE
Does it support elasticsearch 6?

### ISSUE THREAD

**Issue by ctrngk** [InnerSearch/vue-innersearch#19]
I test the [innerSearch-starter-app demo](https://github.com/InnerSearch/innerSearch-starter-app) and it works very well. However, the demo server is running elasticsearch 5.x.  When I run 6.x,  I encountered following error in browser:

- Failed to load http://localhost:9200/bank/_doc/_search: Request header field Authorization is not allowed by Access-Control-Allow-Headers in preflight response.

When I roughly look into the source code, I am not able to fix it. I suspect it does not support 6.x.
FYI https://www.elastic.co/blog/strict-content-type-checking-for-elasticsearch-rest-requests

**Comment by PierreKircher** [comment]
thats a elasticsearch config setting not exactly innersearch based - 
add :

```
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-headers: "X-Requested-With, Content-Type, Content-Length, X-User Authorization"

http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE.
http.detailed_errors.enabled: true
```

to the end of your elasticsearch.yml and call it a day 
beware **THIS IS HIGHLY INSECURE!!!** 
and should just be used in local dev

for production get xpack or some other security mechanism

**Comment by TrimA74** [comment]
vue-innersearch works with Elasticsearch 6
